import * as React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans, shadowsIntoLight } from "@/lib/fonts";
import { cn } from "../lib/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          shadowsIntoLight.variable,
          "antialiased"
        )}
      >
        {props.children}
      </body>
    </html>
  );
}
